6.Form/6-3/project2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('travels/', include('travels.urls')),
]

6.Form/6-3/travels/urls.py
from django.urls import path
from . import views

app_name = 'travels'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

6.Form/6-3/travels/models.py
from django.db import models

# Create your models here.
class Travel(models.Model):
    location = models.CharField(max_length=10)
    plan = models.TextField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    

6.Form/6-3/travels/forms.py
from django import forms
from .models import Travel

class TravelForm(forms.ModelForm):
    location = forms.CharField(
        max_length=10,
        widget=forms.TextInput(attrs={'placeholder': 'ex) 제주도'}))
    plan = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'ex) 여행 계획을 입력하세요'}))
    start_date = forms.DateTimeField(
        widget=forms.TextInput(attrs={'placeholder': 'ex) 2022-02-22'}))
    end_date = forms.DateTimeField(
        widget=forms.TextInput(attrs={'placeholder': 'ex) 2022-02-22'}))
    
    class Meta:
        model = Travel
        fields = '__all__'

6.Form/6-3/travels/views.py
from django.shortcuts import render, redirect
from .models import Travel
from .forms import TravelForm

# Create your views here.
def index(request):
    travels = Travel.objects.all()
    context = {
        'travels': travels
    }
    return render(request, 'travels/index.html', context)


def create(request):
    if request.method == 'POST':
        form = TravelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('travels:index')
    else:
        form = TravelForm()
    context = {
        'form': form,
    }
    return render(request, 'travels/create.html', context)


from django.http import Http404
def detail(request, pk):
    try:
        travel = Travel.objects.get(pk=pk)
    except Travel.DoesNotExist:
        raise Http404("Travel does not exist")
        
    context = {
        'travel': travel,
    }
    return render(request, 'travels/detail.html', context)


def delete(request, pk):
    travel = Travel.objects.get(pk=pk)
    travel.delete()
    return redirect('travels:index')


def update(request, pk):
    travel = Travel.objects.get(pk=pk)
    if request.method == 'POST':
        form = TravelForm(request.POST, instance=travel)
        if form.is_valid():
            travel = form.save()
            return redirect('travels:detail', travel.pk)
    else:
        form = TravelForm(instance=travel)
    context = {
        'travel': travel,
        'form': form,
    }
    return render(request, 'travels/update.html', context)

6.Form/6-3/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div class='container'>
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

6.Form/6-3/travels/templates/travels/create.html
{% extends "base.html" %}

{% block content %}
<h1>CREATE</h1>
<form action="{% url "travels:create" %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="제출">
</form>
<hr>
<a href="{% url "travels:index" %}">[BACK]</a>
{% endblock content %}

6.Form/6-3/travels/templates/travels/detail.html
{% extends "base.html" %}

{% block content %}
<h1>DETAIL</h1>
<h2>{{travel.pk}}번째 글</h2>
<hr>

<div>
    <p>장소 : {{travel.location}}</p>
    <p>계획 : {{travel.plan}}</p>
    <p>시작일 : {{travel.start_date}}</p>
    <p>종료일 : {{travel.end_date}}</p>
</div>
<hr>
<form action="{% url "travels:delete" travel.pk %}">
    {% csrf_token %}
    <input type="submit" value="DELETE">
</form>
<a href="{% url "travels:update" travel.pk %}">[UPDATE]</a>
<hr>
<a href="{% url "travels:index" %}">[BACK]</a>
{% endblock content %}

6.Form/6-3/travels/templates/travels/index.html
{% extends "base.html" %}

{% block content %}
<h1>travels</h1>
<a href="{% url "travels:create" %}">CREATE</a>
<hr>
{% for travel in travels %}
<a href="{% url "travels:detail" travel.pk %}"> {{travel.pk}}번째 글 </a>
<hr>
{% endfor %}
{% endblock content %}

6.Form/6-3/travels/templates/travels/update.html
{% extends "base.html" %}

{% block content %}
<h1>UPDATE</h1>
<form action="{% url "travels:update" travel.pk%}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="제출">
</form>
<hr>
<a href="{% url "travels:detail" travel.pk %}">[BACK]</a>
{% endblock content %}