7.Media&Static/7-3/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('<int:pk>/delete',views.delete,name="delete"),
    path('<int:pk>/update',views.update,name="update"),
    path('create/',views.create,name="create"),
    path('<int:pk>/',views.detail,name="detail"),
    path('',views.index,name="index"),
]

7.Media&Static/7-3/articles/models.py
from PIL import Image
from io import BytesIO
from django.db import models
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    image = models.ImageField(upload_to='article_thumbnails/', blank=True, null=True)  # 썸네일 필드 추가
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def save(self, *args, **kwargs):
        if self.image:
            image = Image.open(self.image)
            if image.width > 100 or image.height > 100:
                output = BytesIO()
                image.thumbnail((100, 100))
                image.save(output, format='JPEG', quality=90)
                output.seek(0)
                self.image = InMemoryUploadedFile(output, 'ImageField', f"{self.image.name.split('.')[0]}_thumbnail.jpg", 'image/jpeg', sys.getsizeof(output), None)
        super(Article, self).save(*args, **kwargs)

7.Media&Static/7-3/articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    
    class Meta:
        model = Article
        fields = '__all__'



7.Media&Static/7-3/articles/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Article
from .forms import ArticleForm
from django.views.decorators.http import require_POST, require_http_methods, require_safe

# Create your views here.

@require_safe
def index(request):
    articles = Article.objects.all()
    context = {
        'articles':articles
    }
    return render(request,'articles/index.html',context)

@require_http_methods(["GET","POST"])
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail',article.pk)
    else:
        form = ArticleForm()
    context={
        'form':form
    }
    return render(request,'articles/create.html',context)

@require_safe
def detail(request,pk):
    article = get_object_or_404(Article,pk=pk)
    context = {
        'article':article,
    }
    return render(request,'articles/detail.html',context)

@require_POST
def delete(request,pk):
    article = get_object_or_404(Article,pk=pk)
    article.delete()
    return redirect("articles:index")

@require_http_methods(["GET","POST"])
def update(request,pk):
    article = get_object_or_404(Article,pk=pk)
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES, instance = article)
        if form.is_valid():
            form.save()
            return redirect("articles:detail",article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'article':article,
        'form':form,
    }
    return render(request,"articles/update.html",context)


7.Media&Static/7-3/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock %}

7.Media&Static/7-3/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h2>DETAIL</h2>
  <h3>{{ article.pk }} 번째 글</h3>
  <hr>
    <p>제목 : {{ article.title }}</p>
    <p>내용 : {{ article.content }}</p>
    <p>만든시간 : {{ article.created_at }}</p>
    <p>수정시간 : {{ article.updated_at }}</p>
  <form action="{% url 'articles:delete' article.pk%}" method="POST">
    {% csrf_token %}
    <input type="submit" value = "DELETE">
    
  </form>
  <a href="{% url 'articles:update' article.pk%}">[UPDATE]</a>
  <hr>
  
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock  %}

7.Media&Static/7-3/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Article</h1>
  <a href="{% url 'articles:create' %}">CREATE</a>
  <hr>
  {% for article in articles %}
    {% if article.image %}  {# 이미지 필드가 비어있지 않은 경우에만 썸네일 표시 #}
      <img src="{{ article.image.url }}" alt="썸네일" width="100" height="100">
    {% endif %}
    <p>제목 : {{ article.title }}</p>
    <p>내용 : {{ article.content }}</p>
    <a href="{% url 'articles:detail' article.pk %}">[detail]</a>
    <hr>
  {% endfor %}

{% endblock %}


7.Media&Static/7-3/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <form action="{% url 'articles:update' article.pk%}" method="POST" enctype="multipart/form-data"> 
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'articles:detail' article.pk%}">[back]</a>
{% endblock %}